services:

    postgres:
        image: postgres
        env_file: .env

    webserver:
        build: ./airflow
        restart: always
        env_file: .env
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow/r2rml_cli:${R2RML_CLI_DIR}
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/r2rml:${R2RML_DATA_DIR}/settings
            - ./input:${R2RML_DATA_DIR}/input
            - ./output:${R2RML_DATA_DIR}/output
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3