version: "3"
services: 
  data_postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
